:sectlinks:
:sectanchors:
:stylesheet: asciidoctor.css
// If not rendered on github, we use fonts for the captions, otherwise, we assign github emojis. DO NOT PUT A BLANK LINE BEFORE THIS, the ICONS don't render.
ifndef::env-github[]
:icons: font
endif::[]
ifdef::env-github[]
:important-caption: :exclamation:
:warning-caption: :x:
:caution-caption: :hand:
:note-caption: :bulb:
:tip-caption: :mag:
endif::[]

= Poker Client Overview

This is a sandbox environment for experimenting with Spring reactive programming to implement a poker client/server for use as a "remote" home game. Our poker group has been forced recently to move our home game online due to social distancing. There are surprisingly few choices out there to manage a private cash or tournament game. This project is an attempt to scratch that itch while giving us an excuse to study reactor and RSocket. This command-line client is using Spring shell to provide a RSocket client to the poker-server (https://github.com/tkvangorder/poker-server)

== TODO
|===
|Percent |Description
|0% |Commands for creating and managing a game.
|0% |Commands to join find and join a game
|===

== Done

- Client-side RSocket security
- Commands for user sign-up and management
- Add a Json converter to the shell to allow Complex objects to be marshaled to/from JSON strings.
- Add a connection manager

== Setup

1. You must have a mongo server running. There is a docker-compose file in the server repo that can be used to startup mongo in a container.
2. Build and run the server (from the root directory of the server) via `./mvnw clean spring-boot:run`
3. Build and run the client (from the root directory of the client) via `./mvnw clean spring-boot:run`
4. From the client you can connect to the server with `connect <host> <port>`
5. You can register a new user after you are connected with `register-user <login ID> <password> <email> <name> <phone>` If there are special characters in a variable, you can surround the variable in quotes.
6. Once your user has been registered, you can now connect as that user via `login <login ID> <password>`
7. You can always type `help` in the client to get available commands and how to use those commands.

